# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24909f459b9d061601689313b68247ba67db4f6b19174839928b178cd5cbc883b42842c6941ec544c93307fed743c0d5d93941feac48621fc15afecb9e76c12a

test:
  secret_key_base: 74dd7c298d8ab90a5cabe09a4d802cdd9a11ae04f345274f0cc00e2bc010faf995e8fb068471ba5435b4999b5bcf5e1d93947e1b1377c8fde48900571a4de051

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
